# Generated by Django 5.1.6 on 2025-05-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='faltas',
            field=models.IntegerField(default=0),
        ),
    ]
