# Generated by Django 5.1.6 on 2025-05-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_vehiculos_faltas'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
